// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: EmployeeManagementService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GrpcDotNetDemo.Contracts.Grpc {

  /// <summary>Holder for reflection information generated from EmployeeManagementService.proto</summary>
  public static partial class EmployeeManagementServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for EmployeeManagementService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EmployeeManagementServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9FbXBsb3llZU1hbmFnZW1lbnRTZXJ2aWNlLnByb3RvGhRFbXBsb3llZU1v",
            "ZGVscy5wcm90bzKSBQoZRW1wbG95ZWVNYW5hZ2VtZW50U2VydmljZRI4CgtH",
            "ZXRFbXBsb3llZRITLkdldEVtcGxveWVlUmVxdWVzdBoULkdldEVtcGxveWVl",
            "UmVzcG9uc2USOwoMR2V0RW1wbG95ZWVzEhQuR2V0RW1wbG95ZWVzUmVxdWVz",
            "dBoVLkdldEVtcGxveWVlc1Jlc3BvbnNlEkEKDkNyZWF0ZUVtcGxveWVlEhYu",
            "Q3JlYXRlRW1wbG95ZWVSZXF1ZXN0GhcuQ3JlYXRlRW1wbG95ZWVSZXNwb25z",
            "ZRJBCg5VcGRhdGVFbXBsb3llZRIWLlVwZGF0ZUVtcGxveWVlUmVxdWVzdBoX",
            "LlVwZGF0ZUVtcGxveWVlUmVzcG9uc2USQQoORGVsZXRlRW1wbG95ZWUSFi5E",
            "ZWxldGVFbXBsb3llZVJlcXVlc3QaFy5EZWxldGVFbXBsb3llZVJlc3BvbnNl",
            "EkUKFUdldEVtcGxveWVlc1N0cmVhbWluZxIULkdldEVtcGxveWVlc1JlcXVl",
            "c3QaFC5HZXRFbXBsb3llZVJlc3BvbnNlMAESWwoiQnVsa0NyZWF0ZUVtcGxv",
            "eWVlc0NsaWVudFN0cmVhbWluZxIWLkNyZWF0ZUVtcGxveWVlUmVxdWVzdBob",
            "LkJ1bGtDcmVhdGVFbXBsb3llZVJlc3BvbnNlKAESYAopQnVsa0NyZWF0ZUVt",
            "cGxveWVlc0JpZGlyZWN0aW9uYWxTdHJlYW1pbmcSFi5DcmVhdGVFbXBsb3ll",
            "ZVJlcXVlc3QaFy5DcmVhdGVFbXBsb3llZVJlc3BvbnNlKAEwARIvCghHZXRU",
            "b2tlbhIQLkdldFRva2VuUmVxdWVzdBoRLkdldFRva2VuUmVzcG9uc2VCIKoC",
            "HUdycGNEb3ROZXREZW1vLkNvbnRyYWN0cy5HcnBjYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::GrpcDotNetDemo.Contracts.Grpc.EmployeeModelsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
